import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import {
  GalleryLanding,
  TopLineSinglePage,
  GalleryContent,
} from '@/components/generic'

const Journal: NextPage = () => {
  return (
    <>
      <Head>
        <title>Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <TopLineSinglePage />
        <GalleryLanding />
        <GalleryContent />
      </BaseLayout>
    </>
  )
}

export default Journal
