import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import {
  // CardGallery,
  TopLinePageContent,
} from '@/components/generic'
import { SectionBlock } from '@/components/layouts/SectionBlock'

const Tags: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tags</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <TopLinePageContent />
          {/*<CardGallery galleryList={fixtures} />*/}
        </SectionBlock>
      </BaseLayout>
    </>
  )
}

export default Tags
