import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import {
  // CardGallery,
  // HeroFilters,
  TopLinePageContent,
} from '@/components/generic'
// import { useRouter } from 'next/router'
import { CategoryLanding } from '@/components/pages'
import { SectionBlock } from '@/components/layouts/SectionBlock'
import { Loader } from '@/components/widgets/LoaderWidget'
// import { useBreakpoint } from '@/hooks/useBreakpoint'
// import { breakpoints, BreakpointsEnum } from '@/src/theme'

const CategorySinglePage: NextPage<{ slug?: string }> = () => {
  // const { query } = useRouter()
  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <TopLinePageContent />
          <CategoryLanding />
          <Loader />
          {/*<CardGallery cards={fixtures} title={String(query.slug)} />*/}
        </SectionBlock>
      </BaseLayout>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  return { props: { slug: context.query.slug } }
}

export default CategorySinglePage
