import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { CardGallery, TopLinePageContent } from '@/components/generic'
import { SectionBlock } from '@/components/layouts/SectionBlock'
import { addApolloState, initializeApollo } from '@/graphql/apollo'
import { listEmployee } from '@/graphql/queries.graphql'
import {
  ListEmployee_listEmployee,
  ListEmployee_listEmployee_edges,
  ListEmployee_listEmployee_edges_node,
} from '@/graphql/types/ListEmployee'

const fixtures = [
  { id: '222dsadas', slug: 'one-project-time', best: 1 },
  { id: 'asddsad222sadasd', slug: 'two-project-time', best: 0 },
  { id: 'asdsad3242asd', slug: 'three-project-time', best: 0 },
  { id: 'asdsdadasfffsadasd', slug: 'four-project-time', best: 0 },
  { id: '222dsadassssd', slug: 'one-project-time', best: 1 },
  { id: 'asddsad222sadasssdsdsd', slug: 'two-project-time', best: 0 },
  { id: 'asdsad3242asdssdss', slug: 'three-project-time', best: 0 },
  { id: 'asdsdadasfffsadadsdsdsd', slug: 'four-project-time', best: 0 },
]

const Employee: NextPage<{
  listEmployee: ListEmployee_listEmployee
  galleryList: Array<ListEmployee_listEmployee_edges_node>
}> = ({ listEmployee, galleryList }) => {
  console.log('data', listEmployee)
  console.log('galleryList', galleryList)
  return (
    <>
      <Head>
        <title>Ladies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <TopLinePageContent />
        </SectionBlock>
        <SectionBlock>
          <CardGallery
            counter={listEmployee.totalCount}
            galleryList={galleryList}
            cards={galleryList}
            title={'Ladies'}
          />
        </SectionBlock>
      </BaseLayout>
    </>
  )
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const apolloClient = initializeApollo()
  const { data } = await apolloClient.query({
    query: listEmployee,
    variables: { first: 10 },
  })

  return addApolloState(apolloClient, {
    props: {
      listEmployee: data.listEmployee,
      galleryList: data.listEmployee.edges.map(
        (v: ListEmployee_listEmployee_edges) => v.node
      ),
    },
  })
}
export default Employee
