import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { TopLinePageContent, SinglePageContent } from '@/components/generic'
import { SectionBlock } from '@/components/layouts/SectionBlock'
import { addApolloState, initializeApollo } from '@/graphql/apollo'
import { getEmployee } from '@/graphql/queries.graphql'
import { ListEmployee_listEmployee_edges_node } from '@/graphql/types/ListEmployee'

const GalleryItem: NextPage<{
  employee: ListEmployee_listEmployee_edges_node
}> = ({ employee }) => {
  console.log('employee', employee)
  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <TopLinePageContent />
        </SectionBlock>

        <SectionBlock>
          <SinglePageContent />
        </SectionBlock>
      </BaseLayout>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const id = query.slug
  const apolloClient = initializeApollo()

  const { data } = await apolloClient.query({
    query: getEmployee,
    variables: { id },
  })

  // const { data: posts } = await apolloClient.query({
  //   query: listPosts,
  //   variables: { first: 10 },
  // })

  // const postListArray =
  //   posts.listPosts.edges.map((edge: NodePost<PostEdge>) => edge.node) || []

  return addApolloState(apolloClient, {
    props: {
      employee: data.getEmployee,
      // posts: postListArray,
    },
  })
}
export default GalleryItem
