import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { CreateHowPage, TopLineSinglePage } from '@/components/generic'

const CreateRequestPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create request rage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <TopLineSinglePage />
        <CreateHowPage />
      </BaseLayout>
    </>
  )
}

export default CreateRequestPage
