import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import {
  // CardGallery,
  // HeroFilters,
  TopLinePageContent,
} from '@/components/generic'

// import { CategoryLanding } from '@/components/pages'
import { SectionBlock } from '@/components/layouts/SectionBlock'
import { Loader } from '@/components/widgets/LoaderWidget'
// import { useBreakpoint } from '@/hooks/useBreakpoint'
// import { breakpoints, BreakpointsEnum } from '@/src/theme'

const CategoryAllPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Categories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <TopLinePageContent />
          <Loader />
          {/*<CategoryLanding />*/}
          {/*<CardGallery cards={fixtures} title={'All'} />*/}
        </SectionBlock>
      </BaseLayout>
    </>
  )
}

export default CategoryAllPage
