import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { SinglePostContent, TopLinePageContent } from '@/components/generic'
import { SectionBlock } from '@/components/layouts/SectionBlock'

const Post: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <TopLinePageContent />
          <SinglePostContent />
        </SectionBlock>
      </BaseLayout>
    </>
  )
}

export default Post
