import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { TopLineSinglePage } from '@/components/generic'

const fixtures = [
  { id: '222dsadas', slug: 'one-project-time', best: 1 },
  { id: 'asddsad222sadasd', slug: 'two-project-time', best: 0 },
  { id: 'asdsad3242asd', slug: 'three-project-time', best: 0 },
  { id: 'asdsdadasfffsadasd', slug: 'four-project-time', best: 0 },
  { id: '222dsadassssd', slug: 'one-project-time', best: 1 },
  { id: 'asddsad222sadasssdsdsd', slug: 'two-project-time', best: 0 },
  { id: 'asdsad3242asdssdss', slug: 'three-project-time', best: 0 },
  { id: 'asdsdadasfffsadadsdsdsd', slug: 'four-project-time', best: 0 },
]
const Gallery: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <TopLineSinglePage />
      </BaseLayout>
    </>
  )
}

export default Gallery
