import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { CardGallery } from '@/components/generic'
import { useStoreon } from '@/store/index'
const Favorites: NextPage = () => {
  const {
    favorites: { items },
  } = useStoreon('favorites')

  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <CardGallery cards={items} />
      </BaseLayout>
    </>
  )
}

export default Favorites
