import type { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { HeroBanner } from '@/components/generic/HeroBanner'
import { HeroFilters } from '@/components/generic/HeroFilters'
import { SalonCard } from '@/components/generic/SalonCard'
import { ContentCardRow } from '@/components/generic/ContentCardRow'
import {
  Card,
  MapSection,
  PostCard,
  PostCardWide,
  PostList,
} from '@/components/generic'
import { SwiperSlide } from 'swiper/react'
import { ShowNewItems } from '@/components/generic/ShowNewItems'
const fixtures = [
  { id: '222dsadas', slug: 'one-project-time', best: 1 },
  { id: 'asddsad222sadasd', slug: 'two-project-time', best: 0 },
  { id: 'asdsad3242asd', slug: 'three-project-time', best: 0 },
  { id: 'asdsdadasfffsadasd', slug: 'four-project-time', best: 0 },
  { id: 'asdxfsadasd', slug: 'four-project-time', best: 0 },
  { id: 'asdsdadvadasd', slug: 'four-project-time', best: 0 },
  { id: 'xfffsadasd', slug: 'four-project-time', best: 0, tag: 'dsd' },
]
import { initializeApollo } from '@/lib/apollo'
import { typeDefs } from '@/lib/schema'
import { GET_LAUNCHES } from './launches'

const Home: NextPage = ({ props }) => {
  console.log('data', props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <HeroBanner />
        <HeroFilters />
        {/*<CategoryScroll />*/}

        <ShowNewItems itemsToShow={[4, 3, 2, 1]} title={'New'} />

        <ContentCardRow
          title="Salons"
          counter={535}
          counterTitle="All salons"
          itemsToShow={[3, 3, 2, 1]}
        >
          {fixtures.map((item) => (
            <SwiperSlide key={item.id}>
              <SalonCard {...item} inSwipe />
            </SwiperSlide>
          ))}
        </ContentCardRow>

        <ContentCardRow
          title="Private ladies"
          counter={535}
          counterTitle="All private ladies"
          itemsToShow={[4, 3, 2, 1]}
        >
          {fixtures.map((item) => (
            <SwiperSlide key={item.id}>
              <Card {...item} tagTitle={item.tag} margin="0 15px 0 0" inSwipe />
            </SwiperSlide>
          ))}
        </ContentCardRow>

        <ContentCardRow
          title="New posts"
          counter={34}
          counterTitle="All posts"
          itemsToShow={[4, 3, 2, 1]}
        >
          {fixtures.map((item) => (
            <SwiperSlide key={item.id}>
              <PostCard {...item} tagTitle={item.tag} inSwipe />
            </SwiperSlide>
          ))}
        </ContentCardRow>
        <MapSection />
        <ContentCardRow
          title="New posts"
          counter={23}
          counterTitle="All posts"
          itemsToShow={[2, 2, 2, 1]}
        >
          {fixtures.map((item) => (
            <SwiperSlide key={item.id}>
              <PostCardWide {...item} tagTitle={item.tag} inSwipe />
            </SwiperSlide>
          ))}
        </ContentCardRow>
        <PostList title="New posts" counter={23} counterTitle="All posts" />
      </BaseLayout>
    </>
  )
}

export async function getServerSideProps() {
  const apolloClient = initializeApollo()

  const { data } = await apolloClient.query({
    query: GET_LAUNCHES,
  })
  console.log('data', data)
  return {
    props: { data },
  }
}

export default Home
