import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { MainFilters } from '@/components/generic/MainFilters/MainFilters'

const FaqPageNext: NextPage = () => {
  return (
    <>
      <Head>
        <title>Filters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <MainFilters />
      </BaseLayout>
    </>
  )
}

export default FaqPageNext
