import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { MainFilters } from '@/components/generic/MainFilters/MainFilters'
import { SectionBlock } from '@/components/layouts/SectionBlock'
import { useQuery } from '@apollo/client'
import {
  ListEmployee,
  ListEmployee_listEmployee_edges,
  ListEmployeeVariables,
} from '@/graphql/types/ListEmployee'
import {
  listEmployee,
  listEmployee as listEmployeeQuery,
} from '@/graphql/queries.graphql'
import { Loader } from '@/components/widgets/LoaderWidget'
import { useRouter } from 'next/router'
import { addApolloState, initializeApollo } from '@/graphql/apollo'
import { findAndLoadGraphQLConfig } from '@graphql-codegen/cli'
// import { EmployeeFilterSort } from '@/graphql/types/ListEmployee'

const SearchPage: () => JSX.Element = () => {
  return (
    <>
      <Head>
        <title>Filters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <MainFilters />
        </SectionBlock>
      </BaseLayout>
    </>
  )
}
// export const getServerSideProps: GetServerSideProps = async ({ query }) => {
//   const apolloClient = initializeApollo()
//   const { data } = await apolloClient.query({
//     query: listEmployee,
//     // variables: { first: 10 },
//   })
//
//   console.log('query', query)
//
//   return addApolloState(apolloClient, {
//     props: {
//       query,
//       listEmployee: data.listEmployee,
//       galleryList: data.listEmployee.edges.map(
//         (v: ListEmployee_listEmployee_edges) => v.node
//       ),
//     },
//   })
// }
export default SearchPage
