import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { GalleryLanding, TopLinePageContent } from '@/components/generic'
import { SupportPage as SupportPageContent } from '@/components/pages'

const SupportPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Support Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <TopLinePageContent />
        <GalleryLanding
          title="Support"
          text="Eroguide is a professional nude photographer.
At the invitation of massage parlors and private masseuses, I visited several thousand girls - I did photo shoots, videos and interviews. Over time, I added the ability to post profiles with my own photos, but most of them still take photos myself."
        />
        <SupportPageContent />
      </BaseLayout>
    </>
  )
}

export default SupportPage
