import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import { TopLinePageContent } from '@/components/generic'
import { SupportPage as SupportPageContent } from '@/components/pages'
import { SectionBlock } from '@/components/layouts/SectionBlock'
const SupportPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Support Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <SectionBlock>
          <TopLinePageContent />
          <SupportPageContent />
        </SectionBlock>
      </BaseLayout>
    </>
  )
}

export default SupportPage
