import { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from '@/components/layouts/BaseLayout'
import {
  CardGallery,
  CategoryScroll,
  HeroBanner,
  HeroFilters,
} from '@/components/generic'

const Salons: NextPage = () => {
  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>SALONS PAGE</BaseLayout>
    </>
  )
}

export default Salons
